inputs:
  path:
    default: .
  files:
    default: "**/*"
  source:
    default: ${{ github.server_url }}/${{ github.repository }}
  image:
    default: ghcr.io/${{ github.repository_owner }}/features/*
  latest:
    default: true
runs:
  using: composite
  steps:
    - id: main
      run: '"$GITHUB_ACTION_PATH/mainw"'
      shell: bash
      env:
        INPUT_GITHUB_SERVER_URL: ${{ inputs.github-server-url }}
        INPUT_PATH: ${{ inputs.path }}
        INPUT_FILES: ${{ inputs.files }}
        INPUT_REPOSITORY: ${{ inputs.repository }}
        INPUT_IMAGE: ${{ inputs.image }}
        INPUT_LATEST: ${{ inputs.latest }}
