name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - .gitignore
      - .gitattributes
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - .gitignore
      - .gitattributes
      - LICENSE
      - README.md
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency: ${{ github.workflow }}
jobs:
  test-action:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oras-project/setup-oras@v1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          path: test
          image: ghcr.io/${{ github.repository }}/*
      - run: |
          pushd "$(mktemp -d)"
          oras manifest fetch ghcr.io/${{ github.repository }}/hello:latest | jq
          oras pull ghcr.io/${{ github.repository }}/hello:latest
          tree -a
          tar -xvf devcontainer-feature-hello.tgz
          tree -a
          jq '' devcontainer-feature.json
          cat install.sh
      - run: |
          pushd "$(mktemp -d)"
          oras manifest fetch ghcr.io/devcontainers/features/node:latest | jq
          oras pull ghcr.io/devcontainers/features/node:latest
          tree -a
          tar -xvf devcontainer-feature-node.tgz
          tree -a
          jq '' devcontainer-feature.json
          cat install.sh
